stages:
  - all

variables:
  GIT_SUBMODULE_STRATEGY: recursive

backend:
  only:
    - merge_requests
  except:
    variables:
      - $CI_MERGE_REQUEST_TITLE =~ /^Draft/
  stage: all
  image: xolvionl/laravel:minimal
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "git@gitlab.com:"
  script:
    - composer install
    - composer validate --strict
    - composer larastan
    - composer format-dry
    - composer test
